### ISSUE TITLE
AMP issue: Images

### ISSUE THREAD

**Issue by staticlover** [dim0627/hugo_theme_robust#13]
Hello,

I've been testing your theme and it is really a great theme. Congratulations for developing it. Almost everything is working fine except images in AMP. Whenever I paste the shortcode thinking images will be rendered separately as < img ....> and < amp-img ... >, however, that doesn't happen. It only renders the image as < img ...> in both regular and AMP pages.

Please help me fix that.

**Comment by dim0627** [comment]
could not reproduced
