### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [dim0627/hugo_theme_robust#34]
Hello yet yet again:)

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37679929-7475b8a4-2c93-11e8-9b99-3ccf96d278d3.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by dim0627** [comment]
oops!Thanks!
Can you make PR?

Adds this property for `img` without figure tag.
https://github.com/dim0627/hugo_theme_robust/blob/master/layouts/partials/styles.css#L407

**Comment by paskal** [comment]
I'm not very good at css — I'll sure fix my problem, but might break something else and won't notice that.
