### ISSUE TITLE
Not working with the latest version

### ISSUE THREAD

**Issue by takameron** [dim0627/hugo_theme_robust#36]
I think that this theme is wonderful.
Thank you!

I tried to build with HUGO version 0.42.2.
However, in the "LATESTS" part of the sidebar, all pages of the tag etc. are output.
Is the version too new?

**Comment by dim0627** [comment]
Hi

Yes, `{{ .Pages }}` containing not single page object in newest versions Hugo.
I know that behavior but does not fixed yet ;(

**Comment by dim0627** [comment]
@t-iwabuchi 
Please check it again after the upgrade theme versions :)

**Comment by takameron** [comment]
It works well.
Thank you.
