### ISSUE TITLE
今後のメンテナンスについて

### ISSUE THREAD

**Issue by ress997** [dim0627/hugo_theme_robust#39]
テーマファイルをまだ使用してる人が存在している中でメンテナンスがされないことは悲しいことです。

そこで組織化し今後もメンテナンスできないかと考えてます。

@dim0627 はどう考えているのか教えて欲しいです。

**Comment by dim0627** [comment]
@ress997 

ご提案ありがとうございます！
ちょっと僕の方ですでにHugoの激しい更新を追う余力がなく（僕もすでにHugoを使ってないので）、今の所メンテは難しそうなのとHugoを使っていくモチベーションがないというのが現状です。

@ress997 さんの方でフォーク頂いているようなのでREADMEでそちらに誘導するのもありかなと思っていますが、とはいえ気が向いたらバージョン追従する、くらいの対応はしてもいいかなという気もしています

**Comment by ress997** [comment]
> @ress997 さんの方でフォーク頂いているようなのでREADMEでそちらに誘導するのもありかなと思っています

ress997 でフォークしたものはまだ変更を施してないので org になったら PR を送ろうと思ってました。

とりあえず #35 の解決、Font Awesome 5を使用するなどこのリポジトリで変更した方が良さそうなものは PR を送らせていただきます。

**Comment by dim0627** [comment]
おお、なるほど、ありがとうございます！
お手数おかけしてもうしわけないですが、とても助かります 🙏 
僕の方も修正が必要そうなところがあったらIssue化して対応できるところはしていこうと思います

**Comment by ress997** [comment]
@dim0627 `README.md` の
> This theme is no longer maintained.

は変更しますか？

**Comment by ress997** [comment]
とりあえず私が対応できそうなところはメンテナンスしていきます
