### ISSUE TITLE
Menu option

### ISSUE THREAD

**Issue by ekoome** [dim0627/hugo_theme_robust#4]
Really nice template. 

Is it possible to add a menu option at the top - to the right?

Eric

**Comment by dim0627** [comment]
Thanks

I do not have menu function in this theme, that mean me to add it?
and can you create pull requests?

**Comment by ekoome** [comment]
Sure. By the way, have you changed the site font? Preferred the previous font. Which font were you previously using and how do I enable it?

**Comment by dim0627** [comment]
OK, I added font settings to config.toml.

Please try this.
[dim0627/hugo_theme_robust](https://github.com/dim0627/hugo_theme_robust#configtoml-example)

```
[params]
  # Fonts settings.
  googlefonts = "https://fonts.google.com/specimen/Open+Sans|Marcellus+SC" # Optional, Include google fonts.
  fontfamily = "'Open+Sans',sans-serif" # Optional, Override body font family.
  logofontfamily = "'Marcellus+SC', cursive" # Optional, Override logo font.
```

Previous font is this.

```
# body
https://fonts.google.com/specimen/Open+Sans
# logo
https://fonts.google.com/specimen/Marcellus+SC
```

**Comment by ekoome** [comment]
Thanks. As for menu, I'm new to Hugo and not sure where to start if I wanted to add menu. I have looked into the Hugo documentation and it is not clear which files need changing.

**Comment by dim0627** [comment]
hmm, I think that is not issue.I do not feel the need to fix this.
Please fork this theme and edit as you like.
Header template is `./layouts/_default/baseof.html`.
