### ISSUE TITLE
Social icons & Disqus

### ISSUE THREAD

**Issue by ekoome** [dim0627/hugo_theme_robust#5]
Hi
Noticed that the social icons have also disappeared. Is it possible to have them configurable to enable after each post (bottom) and on the main page - right hand side?

I enabled disqus but this is not being displayed. Not sure why.

**Comment by dim0627** [comment]
Social icons is not supported now.
Please fork if you needs it.

> I enabled disqus but this is not being displayed

Show your config.toml.

**Comment by dim0627** [comment]
I recommends you using this commit.
69ce3f191a948ddeb323de3e836d0152f8525a30
