### ISSUE TITLE
About pagination of list and article pages

### ISSUE THREAD

**Issue by ress997** [dim0627/hugo_theme_robust#51]
一覧ページと記事ページのページネーションについて相談です。
現在一覧ページでは右に行くほど古くなり記事ページだと右に行くほど新しくなります。
そこで時間の流れを考えた場合、記事と一覧では流れが反対となっており違和感を感じます。
そこで一覧と合わせて記事ページでも右に行くほど古くなるように変更したほうがいいですか？

**Comment by dim0627** [comment]
報告ありがとうございます！
バグですね 😂 
変更してもらって平気です！バグばっかですみません！

**Comment by ress997** [comment]
いえいえ大丈夫です。

しかしこれはバグというより昔のブログはこんな感じだったと思います

**Comment by dim0627** [comment]
いえ、こちら前に一覧の方をIssueもらって直した覚えがあるんですが、その際に記事ページの方と乖離したんだと思います 😭
