### ISSUE TITLE
`link rel=canonical`のタグが2重で出力されている

### ISSUE THREAD

**Issue by zzzmisa** [dim0627/hugo_theme_robust#57]
AMP出力を有効にした場合、AMPページで`link rel="canonical"`のタグが2重で出力されています。
これだと、Google Search ConsoleでAMPエラーになります。
以下は[hugoBasicExample](https://github.com/gohugoio/hugoBasicExample)で試した結果です。

public/amp/about/index.html: 
```
...
<link rel="canonical" href="https://gohugo.io/amp/about/">

<link rel="canonical" type="text/html" href="https://gohugo.io/about/" title="Hugo Themes">
...
```

**Comment by ress997** [comment]
この状態が発生したhugoのバージョンを教えてください

**Comment by zzzmisa** [comment]
@ress997 v0.57.2です。

**Comment by zzzmisa** [comment]
AMPの元になっているオリジナルページでも、`link rel="canonical"`のタグが出力されていたのと、`link rel="amphtml"`のタグが2重に出力されていました。

public/about/index.html: 

```
...
<link rel="canonical" href="https://gohugo.io/about/">

<link rel="amphtml" type="text/html" href="https://gohugo.io/amp/about/" title="Hugo Themes">
...
<link rel="amphtml" type="text/html" href="https://gohugo.io/amp/about/">
...
```

**Comment by ress997** [comment]
すみません急いで対応したいのですがちょっと忙しくて今はできていません

**Comment by zzzmisa** [comment]
@ress997 お気になさらず。メンテナンスありがとうございます！

**Comment by ress997** [comment]
@zzzmisa おまたせしてすみませんとりあえず修正を送りました

**Comment by ress997** [comment]
@zzzmisa とりあえず私の手元で確認しマージしました
