### ISSUE TITLE
Intergrate facebook comment

### ISSUE THREAD

**Issue by bolerap** [dim0627/hugo_theme_robust#6]
Hi Author.
I am using disqus comment on hugo_theme_robust by use disqusShortname in config.toml, but till tody disqus seem not working. I wonder how can i intergrate facebook comment instead disqus.
many thanks.

**Comment by dim0627** [comment]
Hi

> but till tody disqus seem not working.

Is it possible to get to show it to me config.toml?
I set config below, but could not reproduced it .

```
baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
disqusShortname = "disqus"
```

> I wonder how can i intergrate facebook comment instead disqus.

This is not supported this theme.
Please fork and edit if you want it.

Regards.

**Comment by bolerap** [comment]
@dim0627 thanks for your reply, it work well some day ago.
My config
`baseurl = "https://thanhngvpt.github.io/"
title = "David's Notepad"
languageCode = "en-us"

[Params]
Author = "thanhngvpt"
disqusShortname = "thanhngvpt"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

`

**Comment by dim0627** [comment]
Thanks.

`disqusShortname` is not under the params.
https://gohugo.io/extras/comments#adding-disqus-to-a-template
Please `disqusShortname` move to `languageCode` below.

```
baseurl = "https://thanhngvpt.github.io/"
title = "David's Notepad"
languageCode = "en-us"
disqusShortname = "thanhngvpt"

[Params]
Author = "thanhngvpt"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
```

**Comment by bolerap** [comment]
thank @dim0627. But there is an issue i just discovered is. When i try to access my github page https://thanhngvpt.github.io on my home, disqus not working but when i access it at my company, disqus work well. Thus i think the cause of my problem is my internet line not by github page. anyway i will try to change config as you mention above.

**Comment by dim0627** [comment]
hmm, sorry I have no idea :(
But that page ( https://thanhngvpt.github.io/ ) is using old commit of theme.

**Comment by bolerap** [comment]
I just try to move disqusShortname to below languageCode but it does not work, the disqus text link also lost. then i rechange now it working well.

**Comment by dim0627** [comment]
> then i rechange now it working well.

It's solved?
