### ISSUE TITLE
Use Resource Hints?

### ISSUE THREAD

**Issue by ress997** [dim0627/hugo_theme_robust#64]
[Resource Hints](https://triple-underscore.github.io/resource-hints-ja.html) を使用することによってブラウザによっては先読みさせることができますが使用しますか？

正しく使えば先に読み込むため便利ですが、使用しないものを宣言している場合余計なリソース消費が発生するなど問題があるため issue を建てました

**Comment by dim0627** [comment]
いつもご提案ありがとうございます！
いまって使えそうなリソース（外部ドメイン等？）ってありましたっけ？？
僕としてはあっていいかなという気はします 💪

**Comment by ress997** [comment]
Font Awesome や Google Fonts は確実に使っていますね

他にも次のページを事前に読み込んでおくことなどがあります。

**Comment by dim0627** [comment]
あ〜〜〜〜〜その辺使ってましたね 😂 
忘れてましたすみません！すでにテーマにベタ書きで仕込んであるリソースに関しては使ったほうがよさそうですね 🙋‍♂
