### ISSUE TITLE
JSON LD summary produces invalid text when given an '

### ISSUE THREAD

**Issue by danielcompton** [dim0627/hugo_theme_robust#7]
If your summary text includes

`This is a sentence you'd expect to work.`

In the json ld you get:

```
<script type="application/ld+json">
  {
    ...
    "description": "This is a sentence you\x26rsquo;d expect to work."
  }
</script>
```

which fails the parser at https://search.google.com/structured-data/testing-tool/u/0/. I suspect a different filter is needed, but I'm not sure what?

**Comment by dim0627** [comment]
fixed in newest hugo versions.
