### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by iamaya** [dim0627/hugo_theme_robust#9]
I get this error when I try to build the site - 

ERROR 2017/04/14 11:56:53 Error while rendering "taxonomyTerm": template: C:\Projects\hugo\site\themes\hugo_theme_robust\layouts\_default\terms.html:16:48: executing "C:\\Projects\\hugo\\site\\themes\\hugo_theme_robust\\layouts\\_default\\terms.html" at <partial "styles.css"...>: error calling partial: Partial "styles.css" not found
ERROR 2017/04/14 11:56:53 Error while rendering "home": template: C:\Projects\hugo\site\themes\hugo_theme_robust\layouts\_default\list.html:16:48: executing "C:\\Projects\\hugo\\site\\themes\\hugo_theme_robust\\layouts\\_default\\list.html" at <partial "styles.css"...>: error calling partial: Partial "styles.css" not found
ERROR 2017/04/14 11:56:53 Error while rendering "page": template: C:\Projects\hugo\site\themes\hugo_theme_robust\layouts\_default\single.html:16:48: executing "C:\\Projects\\hugo\\site\\themes\\hugo_theme_robust\\layouts\\_default\\single.html" at <partial "styles.css"...>: error calling partial: Partial "styles.css" not found
ERROR 2017/04/14 11:56:53 Error while rendering "404": template: C:\Projects\hugo\site\themes\hugo_theme_robust\layouts\404.html:16:48: executing "C:\\Projects\\hugo\\site\\themes\\hugo_theme_robust\\layouts\\404.html" at <partial "styles.css"...>: error calling partial: Partial "styles.css" not found

Is there a workaround?

**Comment by CountMurphy** [comment]
I also get the same issue

**Comment by dim0627** [comment]
What do you using hugo version?

**Comment by CountMurphy** [comment]
0.20.1

**Comment by dim0627** [comment]
OK, I know error occurence when using hugo 0.20.
I will fix near day, please wait...X(

**Comment by epatr** [comment]
Trying to follow along with http://gohugo.io/overview/quickstart/ and getting the same error.

**Comment by dim0627** [comment]
Yes, I think error occuring by my all theme.

**Comment by dim0627** [comment]
Please try again.

**Comment by iamaya** [comment]
Perfect. Works now ! Thanks 💯

**Comment by dim0627** [comment]
Hi, 
This probrem is solved by hugo v0.20.2.
I will revert this commit.

Thanks, @konart.
https://github.com/dim0627/hugo_theme_aglaus/commit/5db46eb4e507dbdb0527884f28e97a26d3089831#commitcomment-21844848
